# Generated by Django 5.0 on 2024-01-08 05:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='duration2',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(models.F('datetime_saved'),
                                                                           '-',
                                                                           models.F('datetime_add')),
                output_field=models.DurationField()),
        ),
        migrations.AlterField(
            model_name='options',
            name='duration',
            field=models.DurationField(db_index=True),
        ),
    ]
