# Generated by Django 5.0 on 2024-01-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
